version: "3"

services:
    # Primary services to use with this course
    htmlphp: &htmlphp
        image: dbwebb/courserepo:htmlphp
        volumes:
            - ".:/home/dbwebb/repo"
            - "/home/dbwebb/repo/bin"
            - "/home/dbwebb/repo/build"
            - "/home/dbwebb/repo/node_modules"
            - "/home/dbwebb/repo/vendor"
            - "./example/sql/inspect/my.cnf:/home/dbwebb/.my.cnf"

    cli:
        <<: *htmlphp

    server:
        <<: *htmlphp
        ports:
            - "18080:80"

    courserepo:
        image: dbwebb/courserepo:cli
        volumes:
            - ".:/home/dbwebb/repo"
            #- "/home/dbwebb/repo/bin"
            #- "/home/dbwebb/repo/build"
            #- "/home/dbwebb/repo/node_modules"
            #- "/home/dbwebb/repo/vendor"
            - "./example/sql/inspect/my.cnf:/home/dbwebb/.my.cnf"



    # Anax images to test various PHP versions
    # PHP 7.4
    php74: &php74
        image: anax/dev:php74-cli
        volumes:
            - .:/home/anax/repo

    apache74: &apache74
        image: anax/dev:php74-apache
        ports:
            - "18080:80"
        volumes:
            - .:/app
            - ./example/docker/site_default.conf:/etc/apache2/sites-enabled/000-default.conf

    php:
        <<: *php74

    apache:
        <<: *apache74

    # PHP 7.3
    php73:
        image: anax/dev:php73-cli
        volumes:
            - .:/home/anax/repo

    apache73:
        image: anax/dev:php73-apache
        ports:
            - "18080:80"
        volumes:
            - .:/app
            - ./example/docker/site_default.conf:/etc/apache2/sites-enabled/000-default.conf

    # PHP 7.2
    php72:
        image: anax/dev:php72-cli
        volumes:
            - .:/home/anax/repo

    apache72:
        image: anax/dev:php72-apache
        ports:
            - "18080:80"
        volumes:
            - .:/app
            - ./example/docker/site_default.conf:/etc/apache2/sites-enabled/000-default.conf
