version: "3"
services:
    course-any: &course-any
        image: dbwebb/courserepo:course # Should be a fully installed course repo
        volumes:
            - ".:/home/dbwebb/repo"
            - "/home/dbwebb/repo/bin/"
            - "/home/dbwebb/repo/node_modules/"
        ports: [ "10042:80" ]
    course-htmlphp:
        <<: *course-any
        image: dbwebb/courserepo:htmlphp
    course-oophp:
        <<: *course-any
        image: dbwebb/courserepo:oophp
    course-databas:
        <<: *course-any
        image: dbwebb/courserepo:databas
    course:
        image: dbwebb/courserepo
        volumes: [ ".:/home/dbwebb/repo" ]
        ports: [ "10042:80" ]
    base-all:
        image: dbwebb/courserepo:base-all
        volumes: [ ".:/home/dbwebb/repo" ]
        ports: [ "10042:80" ]
    base-apache:
        image: dbwebb/courserepo:base-apache
        volumes: [ ".:/home/dbwebb/repo" ]
        ports: [ "10042:80" ]
    base-php:
        image: dbwebb/courserepo:base-php
        volumes: [ ".:/home/dbwebb/repo" ]
    base-python:
        image: dbwebb/courserepo:base-python
        volumes: [ ".:/home/dbwebb/repo" ]
    base-node:
        image: dbwebb/courserepo:base-node
        volumes: [ ".:/home/dbwebb/repo" ]
    base:
        image: dbwebb/courserepo:base
        volumes: [ ".:/home/dbwebb/repo" ]
    jessie:
        image: dbwebb/courserepo:jessie
        volumes: [ ".:/home/dbwebb/repo" ]
    stretch:
        image: dbwebb/courserepo:stretch
        volumes: [ ".:/home/dbwebb/repo" ]
    buster:
        image: dbwebb/courserepo:buster
        volumes: [ ".:/home/dbwebb/repo" ]
